name: pnpm Example Workflow
on:
  push:
    branches:
      - main
      - stage
      - sandbox
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    strategy:
      matrix:
        node-version: [15]
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v3
      with:
        version: 8
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install

    - name: Build Frontend
      run: npm run build
      working-directory: packages/admin

    - name: Deploy
        uses: reggionick/s3-deploy@v4
        with:
          folder: packages/admin/public
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          delete-removed: true
          no-cache: true
          private: true
          files-to-include: '{.*/**,**}'